"""
    scripts/make_synthetic_geotiff_fixture.jl

Generates a small synthetic GeoTIFF + GLI cover-class GeoTIFF for end-to-end
smoke testing of `scripts/run_from_config.jl` without real data.

Usage:
    julia --project=. scripts/make_synthetic_geotiff_fixture.jl <out-dir>

Produces:
    <out-dir>/synthetic_ortho.tif    — 80×100 RGB GeoTIFF (UInt8) at EPSG:6348
    <out-dir>/synthetic_gli.tif      — same shape, integer cover classes
    <out-dir>/synthetic_run.toml     — RunInputs config wired to the fixture
"""

using Pkg
Pkg.activate(joinpath(@__DIR__, ".."))

using ArchGDAL
const AG = ArchGDAL
using Random

length(ARGS) >= 1 || error("Usage: julia make_synthetic_geotiff_fixture.jl <out-dir>")
const OUT = abspath(ARGS[1])
mkpath(OUT)

const H, W = 80, 100
const GT   = [341300.35, 1.0, 0.0, 4774892.895, 0.0, -1.0]
const CRS_DURHAM_WKT = """PROJCS["NAD83(2011) / UTM zone 19N",GEOGCS["NAD83(2011)",DATUM["NAD83_National_Spatial_Reference_System_2011",SPHEROID["GRS 1980",6378137,298.257222101]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",-69],PARAMETER["scale_factor",0.9996],PARAMETER["false_easting",500000],PARAMETER["false_northing",0],UNIT["metre",1],AUTHORITY["EPSG","6348"]]"""

println("Writing synthetic GeoTIFF fixture in: $OUT")

# Build a meaningful RGB: top half "field" (light), bottom half "vegetation" (dark)
rng = MersenneTwister(20260526)
R = Array{UInt8}(undef, H, W)
G = Array{UInt8}(undef, H, W)
B = Array{UInt8}(undef, H, W)
for j in 1:H, i in 1:W
    if j <= H ÷ 2
        # Field: lightish, slightly yellow-green
        R[j, i] = UInt8(clamp(180 + rand(rng, -15:15), 0, 255))
        G[j, i] = UInt8(clamp(190 + rand(rng, -15:15), 0, 255))
        B[j, i] = UInt8(clamp(140 + rand(rng, -15:15), 0, 255))
    else
        # Forest: dark green
        R[j, i] = UInt8(clamp( 50 + rand(rng, -15:15), 0, 255))
        G[j, i] = UInt8(clamp( 90 + rand(rng, -15:15), 0, 255))
        B[j, i] = UInt8(clamp( 40 + rand(rng, -15:15), 0, 255))
    end
end

ortho_path = joinpath(OUT, "synthetic_ortho.tif")
AG.create(ortho_path; driver = AG.getdriver("GTiff"),
                       width = W, height = H, nbands = 3, dtype = UInt8) do ds
    AG.setgeotransform!(ds, GT)
    try; AG.setproj!(ds, CRS_DURHAM_WKT); catch; end
    AG.write!(ds, permutedims(R), 1)
    AG.write!(ds, permutedims(G), 2)
    AG.write!(ds, permutedims(B), 3)
end
println("  → $ortho_path")

# Synthetic GLI: top half = field (code 2), bottom half split decid (0) / conif (1)
gli = Array{UInt8}(undef, H, W)
for j in 1:H, i in 1:W
    gli[j, i] = if j <= H ÷ 2
        UInt8(2)
    elseif i <= W ÷ 2
        UInt8(0)   # decid
    else
        UInt8(1)   # conif
    end
end
gli_path = joinpath(OUT, "synthetic_gli.tif")
AG.create(gli_path; driver = AG.getdriver("GTiff"),
                     width = W, height = H, nbands = 1, dtype = UInt8) do ds
    AG.setgeotransform!(ds, GT)
    try; AG.setproj!(ds, CRS_DURHAM_WKT); catch; end
    AG.write!(ds, permutedims(gli), 1)
end
println("  → $gli_path")

toml_path = joinpath(OUT, "synthetic_run.toml")
open(toml_path, "w") do io
    println(io, "# Synthetic fixture run config — generated by make_synthetic_geotiff_fixture.jl")
    println(io, "[paths]")
    println(io, "rgb    = \"$(ortho_path)\"")
    println(io, "gli    = \"$(gli_path)\"")
    println(io, "outdir = \"$(joinpath(OUT, "run_output"))\"")
    println(io)
    println(io, "[planning]")
    println(io, "seed                  = 6213")
    println(io, "flightlines_spacing_m = 8.0")  # smaller for the tiny fixture
    println(io, "speed_bounds_mps      = [2.0, 8.0]")
    println(io, "kde_kernel            = \"epanechnikov\"")
    println(io, "kmedoids_k_range      = [2, 5]")
    println(io, "nsample               = 1000")
    println(io, "tree_labels           = [1]   # adjust after reviewing cluster overlays")
    println(io)
    println(io, "[gli_class_codes]")
    println(io, "field = 2")
    println(io, "decid = 0")
    println(io, "conif = 1")
end
println("  → $toml_path")
println("\nNow run:  julia --project=. scripts/run_from_config.jl $toml_path")
