"""
    scripts/make_synthetic_cross_site_fixtures.jl

Generate three small synthetic RGB GeoTIFFs (distinct vegetation/non-vegetation
layouts, real affine geotransforms + CRS, deterministic noise) plus a matching
`cross_site_products.toml` for exercising the lightweight cross-site products
runner and the composer end-to-end WITHOUT any private data.

Usage:
    julia --project=. scripts/make_synthetic_cross_site_fixtures.jl <out-dir> [seed]

Produces in <out-dir>:
    site_a.tif, site_b.tif, site_c.tif   — 3-band UInt8 RGB GeoTIFFs (EPSG:6348)
    products_config.toml                 — config wired to the three fixtures
"""

using Pkg
Pkg.activate(joinpath(@__DIR__, ".."))

using ArchGDAL
const AG = ArchGDAL
using Random

length(ARGS) >= 1 || error("Usage: julia make_synthetic_cross_site_fixtures.jl <out-dir> [seed]")
const OUT  = abspath(ARGS[1])
const SEED = length(ARGS) >= 2 ? parse(Int, ARGS[2]) : 20260716
mkpath(OUT)

const CRS_WKT = """PROJCS["NAD83(2011) / UTM zone 19N",GEOGCS["NAD83(2011)",DATUM["NAD83_National_Spatial_Reference_System_2011",SPHEROID["GRS 1980",6378137,298.257222101]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",-69],PARAMETER["scale_factor",0.9996],PARAMETER["false_easting",500000],PARAMETER["false_northing",0],UNIT["metre",1],AUTHORITY["EPSG","6348"]]"""

# forest?(i,j,H,W,layout) → true where vegetation should sit
forest_at(layout, i, j, H, W) =
    layout === :top_bottom ? (j > H ÷ 2) :
    layout === :left_right ? (i > W ÷ 2) :
    ((i / W) + (j / H) > 1.0)                  # :diagonal

function write_site(path, layout, gt, rng)
    H, W = 60, 80
    R = Array{UInt8}(undef, H, W); G = similar(R); B = similar(R)
    for j in 1:H, i in 1:W
        if forest_at(layout, i, j, H, W)
            R[j,i] = UInt8(clamp( 45 + rand(rng,-15:15), 0, 255))   # dark green forest
            G[j,i] = UInt8(clamp( 95 + rand(rng,-15:15), 0, 255))
            B[j,i] = UInt8(clamp( 40 + rand(rng,-15:15), 0, 255))
        else
            R[j,i] = UInt8(clamp(185 + rand(rng,-15:15), 0, 255))   # light field
            G[j,i] = UInt8(clamp(195 + rand(rng,-15:15), 0, 255))
            B[j,i] = UInt8(clamp(140 + rand(rng,-15:15), 0, 255))
        end
    end
    AG.create(path; driver = AG.getdriver("GTiff"),
                    width = W, height = H, nbands = 3, dtype = UInt8) do ds
        AG.setgeotransform!(ds, gt)
        try; AG.setproj!(ds, CRS_WKT); catch; end
        AG.write!(ds, permutedims(R), 1)
        AG.write!(ds, permutedims(G), 2)
        AG.write!(ds, permutedims(B), 3)
    end
    println("  → $path  [$(layout)]")
    return path
end

# Distinct affine geotransforms (different origins + slightly different m/px).
gts = Dict(
    :a => [341300.35, 0.25, 0.0, 4774892.90, 0.0, -0.25],
    :b => [352110.10, 0.30, 0.0, 4780050.00, 0.0, -0.30],
    :c => [363500.00, 0.20, 0.0, 4791000.50, 0.0, -0.20],
)

rng = MersenneTwister(SEED)
pa = write_site(joinpath(OUT, "site_a.tif"), :top_bottom, gts[:a], rng)
pb = write_site(joinpath(OUT, "site_b.tif"), :left_right, gts[:b], rng)
pc = write_site(joinpath(OUT, "site_c.tif"), :diagonal,   gts[:c], rng)

cfg = joinpath(OUT, "products_config.toml")
open(cfg, "w") do io
    println(io, "# Synthetic cross-site products config — generated by")
    println(io, "# scripts/make_synthetic_cross_site_fixtures.jl (seed=$SEED)")
    println(io, "out_dir = \"products\"")
    println(io)
    println(io, "[defaults]")
    println(io, "seed             = 6213")
    println(io, "nsample          = 1200")
    println(io, "kmedoids_k_range = [2, 4]")
    println(io, "cluster_stride   = 1")
    println(io)
    for (nm, p, lab) in (("Site A", pa, "[1]"), ("Site B", pb, "[1]"), ("Site C", pc, "[1]"))
        println(io, "[[site]]")
        println(io, "name        = \"$nm\"")
        println(io, "geotiff     = \"$(basename(p))\"")
        println(io, "tree_labels = $lab   # omit/[] to select interactively")
        println(io)
    end
end
println("  → $cfg")
println("\nRun the products runner with:")
println("  julia --project=. scripts/make_cross_site_products.jl $cfg")
